# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/mb_demo_ball_locator_0_1.xci
# IP: The module: 'mb_demo_ball_locator_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/ram_pic/ram_pic.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ram_pic || ORIG_REF_NAME==ram_pic} -quiet] -quiet

# IP: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/histogram_y/histogram_y.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==histogram_y || ORIG_REF_NAME==histogram_y} -quiet] -quiet

# IP: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/histogram_x/histogram_x.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==histogram_x || ORIG_REF_NAME==histogram_x} -quiet] -quiet

# IP: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/shift_ram_1bit/shift_ram_1bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shift_ram_1bit || ORIG_REF_NAME==shift_ram_1bit} -quiet] -quiet

# IP: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/shift_ram/shift_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shift_ram || ORIG_REF_NAME==shift_ram} -quiet] -quiet

# IP: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/clk_wiz/clk_wiz.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz || ORIG_REF_NAME==clk_wiz} -quiet] -quiet

# IP: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/shift_ram_16bit/shift_ram_16bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shift_ram_16bit || ORIG_REF_NAME==shift_ram_16bit} -quiet] -quiet

# XDC: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/ram_pic/ram_pic_ooc.xdc

# XDC: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/histogram_y/histogram_y_ooc.xdc

# XDC: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/histogram_x/histogram_x_ooc.xdc

# XDC: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/clk_wiz/clk_wiz.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz || ORIG_REF_NAME==clk_wiz} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/clk_wiz/clk_wiz_ooc.xdc

# IP: C:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/mb_demo_ball_locator_0_1.xci
# IP: The module: 'mb_demo_ball_locator_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/ram_pic/ram_pic.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ram_pic || ORIG_REF_NAME==ram_pic} -quiet] -quiet

# IP: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/histogram_y/histogram_y.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==histogram_y || ORIG_REF_NAME==histogram_y} -quiet] -quiet

# IP: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/histogram_x/histogram_x.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==histogram_x || ORIG_REF_NAME==histogram_x} -quiet] -quiet

# IP: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/shift_ram_1bit/shift_ram_1bit.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shift_ram_1bit || ORIG_REF_NAME==shift_ram_1bit} -quiet] -quiet

# IP: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/shift_ram/shift_ram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shift_ram || ORIG_REF_NAME==shift_ram} -quiet] -quiet

# IP: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/clk_wiz/clk_wiz.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz || ORIG_REF_NAME==clk_wiz} -quiet] -quiet

# IP: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/shift_ram_16bit/shift_ram_16bit.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shift_ram_16bit || ORIG_REF_NAME==shift_ram_16bit} -quiet] -quiet

# XDC: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/ram_pic/ram_pic_ooc.xdc

# XDC: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/histogram_y/histogram_y_ooc.xdc

# XDC: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/histogram_x/histogram_x_ooc.xdc

# XDC: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/clk_wiz/clk_wiz.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz || ORIG_REF_NAME==clk_wiz} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/clk_wiz/clk_wiz_ooc.xdc
