# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/mb_demo.xdc

# Block Designs: bd/mb_demo/mb_demo.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_demo || ORIG_REF_NAME==mb_demo} -quiet] -quiet

# IP: bd/mb_demo/ip/mb_demo_microblaze_0_0/mb_demo_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_demo_microblaze_0_0 || ORIG_REF_NAME==mb_demo_microblaze_0_0} -quiet] -quiet

# IP: bd/mb_demo/ip/mb_demo_microblaze_0_axi_periph_0/mb_demo_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_demo_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_demo_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_demo/ip/mb_demo_microblaze_0_axi_intc_0/mb_demo_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_demo_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_demo_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_demo/ip/mb_demo_microblaze_0_xlconcat_0/mb_demo_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_demo_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mb_demo_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/mb_demo/ip/mb_demo_mdm_1_0/mb_demo_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_demo_mdm_1_0 || ORIG_REF_NAME==mb_demo_mdm_1_0} -quiet] -quiet

# IP: bd/mb_demo/ip/mb_demo_clk_wiz_1_0/mb_demo_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_demo_clk_wiz_1_0 || ORIG_REF_NAME==mb_demo_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb_demo/ip/mb_demo_rst_clk_wiz_1_100M_0/mb_demo_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_demo_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_demo_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mb_demo/ip/mb_demo_dlmb_v10_0/mb_demo_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_demo_dlmb_v10_0 || ORIG_REF_NAME==mb_demo_dlmb_v10_0} -quiet] -quiet

# IP: bd/mb_demo/ip/mb_demo_ilmb_v10_0/mb_demo_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_demo_ilmb_v10_0 || ORIG_REF_NAME==mb_demo_ilmb_v10_0} -quiet] -quiet

# IP: bd/mb_demo/ip/mb_demo_dlmb_bram_if_cntlr_0/mb_demo_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_demo_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_demo_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_demo/ip/mb_demo_ilmb_bram_if_cntlr_0/mb_demo_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_demo_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_demo_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_demo/ip/mb_demo_lmb_bram_0/mb_demo_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_demo_lmb_bram_0 || ORIG_REF_NAME==mb_demo_lmb_bram_0} -quiet] -quiet

# IP: bd/mb_demo/ip/mb_demo_axi_uartlite_0_0/mb_demo_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_demo_axi_uartlite_0_0 || ORIG_REF_NAME==mb_demo_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_demo/ip/mb_demo_axi_gpio_1_0/mb_demo_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_demo_axi_gpio_1_0 || ORIG_REF_NAME==mb_demo_axi_gpio_1_0} -quiet] -quiet

# IP: bd/mb_demo/ip/mb_demo_xbar_0/mb_demo_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_demo_xbar_0 || ORIG_REF_NAME==mb_demo_xbar_0} -quiet] -quiet

# IP: bd/mb_demo/ip/mb_demo_ball_locator_0_1/mb_demo_ball_locator_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_demo_ball_locator_0_1 || ORIG_REF_NAME==mb_demo_ball_locator_0_1} -quiet] -quiet

# IP: bd/mb_demo/ip/mb_demo_axi_timer_0_0/mb_demo_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_demo_axi_timer_0_0 || ORIG_REF_NAME==mb_demo_axi_timer_0_0} -quiet] -quiet

# IP: bd/mb_demo/ip/mb_demo_servo_0_0/mb_demo_servo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_demo_servo_0_0 || ORIG_REF_NAME==mb_demo_servo_0_0} -quiet] -quiet

# IP: bd/mb_demo/ip/mb_demo_axi_iic_0_0/mb_demo_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_demo_axi_iic_0_0 || ORIG_REF_NAME==mb_demo_axi_iic_0_0} -quiet] -quiet

# IP: bd/mb_demo/ip/mb_demo_alinx_ov5640_0_0/mb_demo_alinx_ov5640_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_demo_alinx_ov5640_0_0 || ORIG_REF_NAME==mb_demo_alinx_ov5640_0_0} -quiet] -quiet

# IP: bd/mb_demo/ip/mb_demo_ila_0_0/mb_demo_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_demo_ila_0_0 || ORIG_REF_NAME==mb_demo_ila_0_0} -quiet] -quiet

# IP: bd/mb_demo/ip/mb_demo_axi_iic_1_0/mb_demo_axi_iic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_demo_axi_iic_1_0 || ORIG_REF_NAME==mb_demo_axi_iic_1_0} -quiet] -quiet

# XDC: bd/mb_demo/mb_demo_ooc.xdc
