# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param general.maxThreads 8
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.cache/wt [current_project]
set_property parent.project_path C:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_repo_paths {
  c:/MyFiles/FPGA_Learning/MyMaterial/vivado-library-master
  c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo
} [current_project]
set_property ip_output_repo c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/hdl/mb_demo_wrapper.v
add_files C:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/mb_demo.bd
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_microblaze_0_0/mb_demo_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_microblaze_0_0/mb_demo_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_microblaze_0_0/mb_demo_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_microblaze_0_axi_intc_0/mb_demo_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_microblaze_0_axi_intc_0/mb_demo_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_microblaze_0_axi_intc_0/mb_demo_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_mdm_1_0/mb_demo_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_mdm_1_0/mb_demo_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_clk_wiz_1_0/mb_demo_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_clk_wiz_1_0/mb_demo_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_clk_wiz_1_0/mb_demo_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_rst_clk_wiz_1_100M_0/mb_demo_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_rst_clk_wiz_1_100M_0/mb_demo_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_rst_clk_wiz_1_100M_0/mb_demo_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_dlmb_v10_0/mb_demo_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_dlmb_v10_0/mb_demo_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ilmb_v10_0/mb_demo_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ilmb_v10_0/mb_demo_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_dlmb_bram_if_cntlr_0/mb_demo_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ilmb_bram_if_cntlr_0/mb_demo_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_lmb_bram_0/mb_demo_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_axi_uartlite_0_0/mb_demo_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_axi_uartlite_0_0/mb_demo_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_axi_uartlite_0_0/mb_demo_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_axi_gpio_1_0/mb_demo_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_axi_gpio_1_0/mb_demo_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_axi_gpio_1_0/mb_demo_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_xbar_0/mb_demo_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/ram_pic/ram_pic_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/histogram_y/histogram_y_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/histogram_x/histogram_x_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/clk_wiz/clk_wiz.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_ball_locator_0_1/src/clk_wiz/clk_wiz_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_axi_timer_0_0/mb_demo_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_axi_timer_0_0/mb_demo_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_axi_quad_spi_0_0/mb_demo_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_axi_quad_spi_0_0/mb_demo_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_axi_quad_spi_0_0/mb_demo_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_axi_quad_spi_0_0/mb_demo_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_axi_iic_0_0/mb_demo_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/ip/mb_demo_axi_iic_0_0/mb_demo_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/sources_1/bd/mb_demo/mb_demo_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/constrs_1/imports/new/mb_demo.xdc
set_property used_in_implementation false [get_files C:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/ball_mb.srcs/constrs_1/imports/new/mb_demo.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top mb_demo_wrapper -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mb_demo_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mb_demo_wrapper_utilization_synth.rpt -pb mb_demo_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
