# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/.Xil/Vivado-13256-ZYQ-Mac-Win/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tcpg236-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/clk_wiz {
      C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/clk_wiz {
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/clk_wiz/clk_wiz_clk_wiz.v
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/clk_wiz/clk_wiz.v
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/IIC_module.v
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/IICctrl.v
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/RGB888_to_YCrCb.v
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/average_filter.v
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/hdl/ball_locator_v1_0_S_AXI.v
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/cam_ov7670_read_example.v
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/cam_test.v
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/camera_module.v
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/color_comparator.v
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/erosion_dilation.v
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/iic_driver.v
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/median_filter.v
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/median_filter_rgb888.v
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/middle_comparator.v
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/ov7725_regData.v
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/projection_segment.v
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/shift_RAM_3x3.v
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/shift_RAM_3x3_1bit.v
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/single_color_cmp.v
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/take_color.v
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/top_module.v
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/vga_display_pic.v
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/vga_driver.v
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/vga_module.v
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/hdl/ball_locator_v1_0.v
    }
      rt::read_vhdl -lib blk_mem_gen_v8_4_1 c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/histogram_y/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/histogram_y/synth/histogram_y.vhd
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/histogram_x/synth/histogram_x.vhd
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/shift_ram_1bit/synth/shift_ram_1bit.vhd
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/shift_ram/synth/shift_ram.vhd
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/ram_pic/synth/ram_pic.vhd
      c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/shift_ram_16bit/synth/shift_ram_16bit.vhd
    }
      rt::read_vhdl -lib xbip_utils_v3_0_9 c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/shift_ram_1bit/hdl/xbip_utils_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib c_reg_fd_v12_0_5 c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/shift_ram_1bit/hdl/c_reg_fd_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib c_mux_bit_v12_0_5 c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/shift_ram_1bit/hdl/c_mux_bit_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib c_shift_ram_v12_0_12 c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/repo/ball_locator_1.0/src/shift_ram_1bit/hdl/c_shift_ram_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top ball_locator_v1_0
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/mb/.Xil/Vivado-13256-ZYQ-Mac-Win/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
