# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/ZYNQ_4/OV_VDMA.srcs/sources_1/bd/system/ip/system_alinx_ov5640_0_0/system_alinx_ov5640_0_0.xci
# IP: The module: 'system_alinx_ov5640_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/ZYNQ_4/OV_VDMA.srcs/sources_1/bd/system/ip/system_alinx_ov5640_0_0/src/ila_0/ila_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# XDC: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/ZYNQ_4/OV_VDMA.srcs/sources_1/bd/system/ip/system_alinx_ov5640_0_0/src/ila_0/ila_v6_2/constraints/ila.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/ZYNQ_4/OV_VDMA.srcs/sources_1/bd/system/ip/system_alinx_ov5640_0_0/src/ila_0/ila_0_ooc.xdc

# IP: C:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/ZYNQ_4/OV_VDMA.srcs/sources_1/bd/system/ip/system_alinx_ov5640_0_0/system_alinx_ov5640_0_0.xci
# IP: The module: 'system_alinx_ov5640_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/ZYNQ_4/OV_VDMA.srcs/sources_1/bd/system/ip/system_alinx_ov5640_0_0/src/ila_0/ila_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# XDC: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/ZYNQ_4/OV_VDMA.srcs/sources_1/bd/system/ip/system_alinx_ov5640_0_0/src/ila_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/ZYNQ_4/OV_VDMA.srcs/sources_1/bd/system/ip/system_alinx_ov5640_0_0/src/ila_0/ila_0_ooc.xdc
