webtalk_init -webtalk_dir C:\\MyFiles\\PYNQ_Ball_and_Plate_Sysyem\\vivado_proj\\mb_2\\ctrl.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-12-27 17:26:26" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "l36dbs7o91nbn39v73gunkl1ap" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_30" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "30" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3096 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.449 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1545898008283" -context "sdk\\\\application/1545898008283"
webtalk_add_data -client sdk -key hwid -value "1545897466988" -context "sdk\\\\application/1545898008283"
webtalk_add_data -client sdk -key bspid -value "1545897513596" -context "sdk\\\\application/1545898008283"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1545898008283"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1545898008283"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1545898008283"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1545898008283"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1545898008283"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1545898008283"
webtalk_add_data -client sdk -key projSize -value "85.40625" -context "sdk\\\\application/1545898008283"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1545902786146"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1545902786146"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1545902786146"
webtalk_add_data -client sdk -key DebugCount -value "10" -context "sdk\\\\bsp/1545902786146"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1545902786146"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1545902786146"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1545902786146"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1545902786146"
webtalk_transmit -clientid 1576722986 -regid "" -xml C:\\MyFiles\\PYNQ_Ball_and_Plate_Sysyem\\vivado_proj\\mb_2\\ctrl.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\MyFiles\\PYNQ_Ball_and_Plate_Sysyem\\vivado_proj\\mb_2\\ctrl.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\MyFiles\\PYNQ_Ball_and_Plate_Sysyem\\vivado_proj\\mb_2\\ctrl.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
