set_property IOSTANDARD LVCMOS33 [get_ports OV7725_XCLK_0]
set_property IOSTANDARD LVCMOS33 [get_ports OV7725_HREF_0]
set_property IOSTANDARD LVCMOS33 [get_ports OV7725_PCLK_0]
set_property IOSTANDARD LVCMOS33 [get_ports OV7725_PWND_0]
set_property IOSTANDARD LVCMOS33 [get_ports OV7725_RST_0]
set_property IOSTANDARD LVCMOS33 [get_ports OV7725_SIOC_0]
set_property IOSTANDARD LVCMOS33 [get_ports OV7725_SIOD_0]
set_property IOSTANDARD LVCMOS33 [get_ports OV7725_VSYNC_0]
set_property IOSTANDARD LVCMOS33 [get_ports {OV7725_D_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OV7725_D_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OV7725_D_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OV7725_D_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OV7725_D_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OV7725_D_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OV7725_D_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OV7725_D_0[0]}]
set_property PACKAGE_PIN M18 [get_ports OV7725_XCLK_0]
set_property PACKAGE_PIN N17 [get_ports OV7725_HREF_0]
set_property PACKAGE_PIN M19 [get_ports OV7725_PCLK_0]
set_property PACKAGE_PIN A14 [get_ports OV7725_PWND_0]
set_property PACKAGE_PIN A15 [get_ports OV7725_RST_0]
set_property PACKAGE_PIN R18 [get_ports OV7725_SIOC_0]
set_property PACKAGE_PIN P18 [get_ports OV7725_SIOD_0]
set_property PACKAGE_PIN P17 [get_ports OV7725_VSYNC_0]
set_property PACKAGE_PIN L17 [get_ports {OV7725_D_0[7]}]
set_property PACKAGE_PIN K17 [get_ports {OV7725_D_0[6]}]
set_property PACKAGE_PIN C16 [get_ports {OV7725_D_0[5]}]
set_property PACKAGE_PIN B16 [get_ports {OV7725_D_0[4]}]
set_property PACKAGE_PIN C15 [get_ports {OV7725_D_0[3]}]
set_property PACKAGE_PIN B15 [get_ports {OV7725_D_0[2]}]
set_property PACKAGE_PIN A17 [get_ports {OV7725_D_0[1]}]
set_property PACKAGE_PIN A16 [get_ports {OV7725_D_0[0]}]

set_property PULLUP true [get_ports OV7725_SIOD_0]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets OV7725_PCLK_0]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets OV7725_VSYNC_0]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_data_0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data_0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data_0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data_0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports vga_hsync_0]
set_property IOSTANDARD LVCMOS33 [get_ports vga_vsync_0]
set_property PACKAGE_PIN N19 [get_ports {vga_data_0[11]}]
set_property PACKAGE_PIN J19 [get_ports {vga_data_0[10]}]
set_property PACKAGE_PIN H19 [get_ports {vga_data_0[9]}]
set_property PACKAGE_PIN G19 [get_ports {vga_data_0[8]}]
set_property PACKAGE_PIN D17 [get_ports {vga_data_0[7]}]
set_property PACKAGE_PIN G17 [get_ports {vga_data_0[6]}]
set_property PACKAGE_PIN H17 [get_ports {vga_data_0[5]}]
set_property PACKAGE_PIN J17 [get_ports {vga_data_0[4]}]
set_property PACKAGE_PIN J18 [get_ports {vga_data_0[3]}]
set_property PACKAGE_PIN K18 [get_ports {vga_data_0[2]}]
set_property PACKAGE_PIN L18 [get_ports {vga_data_0[1]}]
set_property PACKAGE_PIN N18 [get_ports {vga_data_0[0]}]
set_property PACKAGE_PIN P19 [get_ports vga_hsync_0]
set_property PACKAGE_PIN R19 [get_ports vga_vsync_0]

set_property IOSTANDARD LVCMOS33 [get_ports en_take_color_i_0]

set_property PACKAGE_PIN T18 [get_ports en_take_color_i_0]

set_property IOSTANDARD LVCMOS33 [get_ports pwm0_0]
set_property PACKAGE_PIN L1 [get_ports pwm0_0]


set_property IOSTANDARD LVCMOS33 [get_ports pwm_out_0_0]
set_property IOSTANDARD LVCMOS33 [get_ports pwm_out_1_0]
set_property PACKAGE_PIN J1 [get_ports pwm_out_0_0]
set_property PACKAGE_PIN H1 [get_ports pwm_out_1_0]



#Pmod Header JXADC
#IIC test
#Sch name = XA1_P
set_property PACKAGE_PIN J3 [get_ports {iic_rtl_scl_io}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {iic_rtl_scl_io}]
#Sch name = XA2_P
set_property PACKAGE_PIN L3 [get_ports {iic_rtl_sda_io}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {iic_rtl_sda_io}]

set_property PULLUP true [get_ports iic_rtl_scl_io]
set_property PULLUP true [get_ports iic_rtl_sda_io]
