# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pynq-z2_v1.0.xdc/pynq-z2_v1.0.xdc

# Block Designs: bd/pynq_design/pynq_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_design || ORIG_REF_NAME==pynq_design} -quiet] -quiet

# IP: bd/pynq_design/ip/pynq_design_processing_system7_0_0/pynq_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_design_processing_system7_0_0 || ORIG_REF_NAME==pynq_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/pynq_design/ip/pynq_design_axi_timer_0_0/pynq_design_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_design_axi_timer_0_0 || ORIG_REF_NAME==pynq_design_axi_timer_0_0} -quiet] -quiet

# IP: bd/pynq_design/ip/pynq_design_axi_timer_1_0/pynq_design_axi_timer_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_design_axi_timer_1_0 || ORIG_REF_NAME==pynq_design_axi_timer_1_0} -quiet] -quiet

# IP: bd/pynq_design/ip/pynq_design_ps7_0_axi_periph_0/pynq_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==pynq_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/pynq_design/ip/pynq_design_rst_ps7_0_100M_0/pynq_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==pynq_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/pynq_design/ip/pynq_design_xlconcat_0_0/pynq_design_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_design_xlconcat_0_0 || ORIG_REF_NAME==pynq_design_xlconcat_0_0} -quiet] -quiet

# IP: bd/pynq_design/ip/pynq_design_xbar_0/pynq_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_design_xbar_0 || ORIG_REF_NAME==pynq_design_xbar_0} -quiet] -quiet

# IP: bd/pynq_design/ip/pynq_design_auto_pc_0/pynq_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_design_auto_pc_0 || ORIG_REF_NAME==pynq_design_auto_pc_0} -quiet] -quiet

# XDC: bd/pynq_design/pynq_design_ooc.xdc
