# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/ZYNQ/ball.srcs/sources_1/bd/pynq_design/ip/pynq_design_auto_pc_0/pynq_design_auto_pc_0.xci
# IP: The module: 'pynq_design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/ZYNQ/ball.srcs/sources_1/bd/pynq_design/ip/pynq_design_auto_pc_0/pynq_design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pynq_design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/ZYNQ/ball.srcs/sources_1/bd/pynq_design/ip/pynq_design_auto_pc_0/pynq_design_auto_pc_0.xci
# IP: The module: 'pynq_design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/MyFiles/PYNQ_Ball_and_Plate_Sysyem/vivado_proj/ZYNQ/ball.srcs/sources_1/bd/pynq_design/ip/pynq_design_auto_pc_0/pynq_design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pynq_design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
